In [15]:
import pandas as pd
products_df = pd.read_csv('products.csv')
departments_df = pd.read_csv('departments.csv')
# order_products_col=["order_id","product_id","add_to_cart_order"]
# order_products_df = pd.read_csv('order_products.csv', usecols=order_products_col)
columns_type={
    'oder_id':'int32',
    'product_id':'int32',
    'add_to_cart_order':'int16',
    'reordered':'int8',
    "product_name":'string'
}
order_products_df = pd.read_csv('order_products.csv',dtype=columns_type)
orders_df = pd.read_csv('orders.csv')
aisles_df = pd.read_csv('aisles.csv')
# df3.isnull().sum()
order_products_df.duplicated()
# order_products_df
orders_df=orders_df.dropna()
# orders_df
dataf1=pd.merge(products_df, departments_df, on="department_id")
dataf2=pd.merge(dataf1,aisles_df,on="aisle_id")
dataf2

,product_id,product_name,aisle_id,department_id,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,pantry,marinades meat preparation
...,...,...,...,...,...,...
49683,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,alcohol,spirits
49684,49685,En Croute Roast Hazelnut Cranberry,42,1,frozen,frozen vegan vegetarian
49685,49686,Artisan Baguette,112,3,bakery,bread
49686,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,pets,cat food care
49687,49688,Fresh Foaming Cleanser,73,11,personal care,facial care

# Merging

In [16]:
dataf5=pd.merge(order_products_df,dataf2,on="product_id")
del dataf5['aisle_id']
del dataf5['department_id']
dataf5.to_csv("merge_of_order_products_dataf2.csv")
dataf5

,order_id,product_id,add_to_cart_order,reordered,product_name,department,aisle
0,2,33120,1,1,Organic Egg Whites,dairy eggs,eggs
1,2,28985,2,1,Michigan Organic Kale,produce,fresh vegetables
2,2,9327,3,0,Garlic Powder,pantry,spices seasonings
3,2,45918,4,1,Coconut Butter,pantry,oils vinegars
4,2,30035,5,0,Natural Sweetener,pantry,baking ingredients
...,...,...,...,...,...,...,...
32434484,3421083,39678,6,1,Free & Clear Natural Dishwasher Detergent,household,dish detergents
32434485,3421083,11352,7,0,Organic Mini Sandwich Crackers Peanut Butter,snacks,crackers
32434486,3421083,4600,8,0,All Natural French Toast Sticks,frozen,frozen breakfast
32434487,3421083,24852,9,1,Banana,produce,fresh fruits
32434488,3421083,5020,10,1,Organic Sweet & Salty Peanut Pretzel Granola ...,snacks,energy granola bars

# What items sell the most ?

In [17]:
most_sell_items=dataf5["product_name"].value_counts()
most_sell_items=pd.DataFrame(most_sell_items)
most_sell_items=most_sell_items.to_csv("most_sell_items.csv")
# all_product_department.nlargest(8, 'count')

# Most selling department

In [18]:
all_product_department=dataf5["department"].value_counts()
all_product_department=pd.DataFrame(all_product_department)
all_product_department.to_csv('all_product_per_department.csv')
all_product_department.nlargest(8, 'count')

                count
department
produce       9479291
dairy eggs    5414016
snacks        2887550
beverages     2690129
frozen        2236432
pantry        1875577
bakery        1176787
canned goods  1068058

# Number of products per aisle

In [19]:
all_product_per_aisle=dataf5["aisle"].value_counts()
all_product_per_aisle=pd.DataFrame(all_product_per_aisle)
# all_product_per_aisle.nlargest( 'count')
all_product_per_aisle.to_csv('all_product_per_aisle.csv')
all_product_per_aisle

                              count
aisle
fresh fruits                3642188
fresh vegetables            3418021
packaged vegetables fruits  1765313
yogurt                      1452343
packaged cheese              979763
...                             ...
eye ear care                   8974
baby bath body care            8581
baby accessories               8160
beauty                         6168
frozen juice                   4853

[134 rows x 1 columns]

# First product added to cart by customers

In [20]:
first_selected_prod=dataf5.groupby("order_id").first()["product_name"].value_counts()
first_selected_prod=pd.DataFrame(first_selected_prod)
first_selected_prod.to_csv('first_selected_prod.csv')
first_selected_prod.nlargest( 3,'count')

                         count
product_name
Banana                  110916
Bag of Organic Bananas   78988
Organic Whole Milk       30927

# When do people order ?

In [21]:
orders_df = pd.read_csv('orders.csv')
orders_df=orders_df.dropna()
orders_df=pd.DataFrame(orders_df)
days={
    0:"Monday",
    1:"Tuesday",
    2:"Wednesday",
    3:"Thursday",
    4:"Friday",
    5:"Saturday",
    6:"Sunday"
}
orders_df["day"]=orders_df["order_dow"].map(days)
# orders_df=orders_df.groupby(orders_df["day"])
orders_df1=orders_df["day"].value_counts()
orders_df1=pd.DataFrame(orders_df1)
orders_df1.to_csv('order_per_day.csv')
orders_df1

            count
day
Monday     562388
Tuesday    552505
Wednesday  439399
Saturday   427295
Sunday     420070
Thursday   411314
Friday     401903

 # How many items do people buy?

In [22]:
orders_df = pd.read_csv('orders.csv')
orders_df2=orders_df["order_id"].count()
print(f"{orders_df2} items people bought")

3421083 items people bought

In [23]:
import pandas as pd
dataf3=pd.merge(order_products_df,orders_df,on="order_id")
# dataf4=pd.merge(orders_df,dataf5,on="order_id")
dataf3.to_csv('merge_of_orders_products_and_orders.csv')
# dataf3.to_csv

# The average of the items per order

In [24]:
# dataf4=dataf3.groupby('user_id')['product_id'].value_counts().sum()
# total_product=dataf2.groupby('product_id').count()
total_order=dataf5.groupby("order_id")['product_name'].count()
total_order_df=total_order.reset_index()
total_order_df.columns=["order_id","product_name"]
total_order_df.to_csv("item_average_per_order.csv", index=False)
# order_products_df.columns=["order_id","product_name"]
# order_products_df.to_csv("item_average_per_order.csv", index=False)
print(total_order.mean())

10.088883421247614

# Average of order per customer

In [25]:
# customers=dataf3.groupby("user_id")['user_id'].value_counts()
# 
order_average_per_user=orders_df.groupby("user_id")['order_id'].count()

order_average_per_user_df = order_average_per_user.reset_index() 
order_average_per_user_df.columns = ['user_id', 'order_count']
order_average_per_user_df.to_csv("order_average_per_user.csv",index=False)
print(order_average_per_user.mean())

16.590367054784224

# Total customers

In [26]:
orders_df = pd.read_csv('orders.csv')
orders_df2=orders_df["user_id"].unique().shape[0]
orders_df2
# print(f"{orders_df2} items people bought")

206209

# All orders

In [27]:
orders_df = pd.read_csv('orders.csv')
orders_df2=orders_df["order_id"].count()
print(f"{orders_df2} items people bought")

3421083 items people bought